<a href="https://colab.research.google.com/github/milaneso69/ECBD-ALEJANDROARENAS/blob/main/Lab00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [16]:

#Conjunto de datos
datos = {
    "usuario" : ["Ana","Luis","Martha", "Carolina","Sofia","Pedro", "Elena","Diego"],
    "edad" : [22,35,28,40,19,31,26,45],
    "ciudad" : ["CDMX","Monterrey","Guadalajara","Puebla","Cancún","Mérida","Tijuana","Toluca"],
    "compras_realizadas" : [5,12,3,29,1,7,4,15],
    "activo" : [True, False, True, True, False, True, False, True],
    "fecha_registro" : ["2026-01-10","2026-01-12","2025-02-10","2025-01-05","2026-02-10","2026-03-15","2025-04-10","2026-01-31"]
}

In [18]:
df = pd.DataFrame(datos)

In [19]:
df.head()

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-12
2    Martha    28  Guadalajara                   3    True     2025-02-10
3  Carolina    40       Puebla                  29    True     2025-01-05
4     Sofia    19       Cancún                   1   False     2026-02-10

In [ ]:
cantidad = 1000000

In [ ]:
import random

In [ ]:
#Datos aleatorios
nombres = ["Juan", "Sofía", "Miguel", "Laura", "Carlos", "Ana", "José", "Isabel"]
ciudades = ["Madrid", "Barcelona", "Sevilla", "Valencia", "Bilbao", "Málaga", "Zaragoza", "Murcia"]
categorias = ["Electrónica", "Ropa", "Hogar", "Libros", "Deportes", "Alimentos", "Juguetes", "Belleza"]

In [ ]:
#Creación del DataFrame
dfMillon = pd.DataFrame ({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "edad" : [random.randint(18,70) for _ in range(cantidad) ],
    "salario" : [round(random.uniform(5000,50000),2) for _ in range(cantidad)],
    "activo" : [random.choice([True, False]) for _ in range(cantidad)],
    "categoria" : [random.choice(ciudades) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2020,2026) for _ in range(cantidad)]
})

In [14]:
dfMillon.dtypes

nombre            object
edad               int64
salario          float64
activo              bool
categoria         object
anio_registro      int64
dtype: object

In [ ]:
dfMillon.memory_usage(deep=True).sum() /1024**2

np.float64(134.3471622467041)