In [1]:
import pandas
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
from sklearn.metrics import ( accuracy_score,
                             confusion_matrix,
                             classification_report,
                             ConfusionMatrixDisplay  )

In [3]:
from numpy import load
from sklearn.datasets import load_iris
#Cargamos el dataset iris
iris=load_iris(as_frame = True)

In [4]:

print (iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [5]:
#Dataframe
dfIris = iris.frame

In [6]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0




#Exploracion de conjunto de datos

In [7]:
dfIris.shape

(150, 5)

In [8]:
dfIris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
#Renombrar la columna target

dfIris.rename(columns= {"target": "especie" }, inplace=True)

In [11]:
dfIris["especie"]= dfIris ["especie"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

In [12]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especie
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [13]:
dfIris.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especie
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

#Identeficar variables predictoras y variables objetivo

In [14]:
#variables predictora
X = dfIris.drop(columns=["especie"])

In [15]:
print("Variables predictoras")
(X.columns)

Variables predictoras

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [16]:
#Variable objetivo
y = dfIris["especie"]

In [17]:
print("Variable objetivo")
(y.name)

Variable objetivo

'especie'

# Dividir los datos en prueba y entrenamiento

# 80% para entrenamiento
# 20% para prueba

In [18]:
X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [19]:
print("X_train", X_Train.shape)
print("X_test", X_Test.shape)
print("y_train", y_Train.shape)
print("y_test", y_Test.shape)

X_train (120, 4)
X_test (30, 4)
y_train (120,)
y_test (30,)

# Escalado de variables

In [20]:
scaler = StandardScaler()

In [21]:
# escalamos las variables
X_Train_escalado = scaler.fit_transform(X_Train)
X_Test_escalado = scaler.transform(X_Test)

In [22]:
print ("Sin escalar")
print (X_Train.head())
print ("Escalado")
print (X_Train_escalado[0:5])

Sin escalar
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
Escalado
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]

# Entrenamiento del modelo KNM

En esta prueba utilizaremos k = 3

In [23]:
modelo = KNeighborsClassifier(n_neighbors=3)

In [24]:
modelo.fit(X_Train_escalado, y_Train)

KNeighborsClassifier(n_neighbors=3)

In [25]:
prediccion = modelo.predict(X_Test_escalado)

In [26]:
print(prediccion [0:10])

['setosa' 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor']

In [27]:
comparacion = pd.DataFrame({"especie real": y_Test.values , "especie predicha": prediccion})

In [28]:
#comparacion.heat()

In [29]:
accuracy = accuracy_score(y_Test, prediccion)
print(f"accuracy/exactitud: {accuracy:.4f}")

accuracy/exactitud: 0.9333

In [30]:
cm = confusion_matrix(y_Test, prediccion)

In [31]:
cm_df = pd.DataFrame(cm, index= modelo.classes_, columns= modelo.classes_)
cm_df

            setosa  versicolor  virginica
setosa          10           0          0
versicolor       0          10          0
virginica        0           2          8

#calsification report
proporciona metricas que permiten evaluar el desempeño de cada clase precision, recall, f1-score, support

In [32]:
print(classification_report(y_Test, prediccion))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30